Repository alibaba/EasyRec, pull requests merged in 2022-04, with the labels that each got.

#149 fea: Add the rec sln tool for modify config
  easy_rec/python/tools/add_feature_info_to_config.py
Labels: ci_test_passed

#137 feat: Add expr feature
  .git_bin_path
  .git_bin_url
  docs/source/eval.md
  docs/source/feature/feature.rst
  docs/source/feature/rtp_fg.md
  docs/source/models/dssm.md
  docs/source/models/dssm_neg_sampler.md
  docs/source/quick_start/mc_tutorial.md
  docs/source/quick_start/mc_tutorial_inner.md
  easy_rec/python/feature_column/feature_column.py
  easy_rec/python/input/input.py
  easy_rec/python/model/dssm.py
  easy_rec/python/protos/feature_config.proto
  easy_rec/python/test/train_eval_test.py
  easy_rec/python/test/util_test.py
  easy_rec/python/utils/expr_util.py
  easy_rec/version.py
  samples/model_config/multi_tower_on_taobao_for_expr.config
Labels: ci_test_passed

#152 [feat]: modify sample weight & add pairwise loss to multi tower model
  docs/source/models/multi_tower.md
  easy_rec/python/compat/feature_column/feature_column_v2.py
  easy_rec/python/input/input.py
  easy_rec/python/model/multi_tower.py
  easy_rec/version.py
  samples/model_config/multi_tower_on_taobao.config
Labels: ci_test_passed

#153 [bugfix]: fix python3 variational dropout
  easy_rec/python/layers/input_layer.py
  easy_rec/python/layers/variational_dropout_layer.py
  setup.cfg
Labels: ci_test_passed

#158 [fix] error when read hive config to evaluate
  easy_rec/python/main.py
Labels: ci_test_passed

#154 [feature]: add py3 test
  .git_oss_config_pub
  .github/workflows/ci_py3.yml
  easy_rec/python/model/multi_tower_bst.py
  easy_rec/python/test/train_eval_test.py
  git-lfs/git_lfs.py
Labels: ci_test_passed

#165 [bugfix]: fix group auc calc sql bug
  docs/source/metrics.md
Labels: ci_test_passed, ci_py3_test_passed

#164 [bugfix]: fix gauc eval online
  easy_rec/python/model/easy_rec_estimator.py
  easy_rec/python/test/train_eval_test.py
  samples/model_config/deepfm_combo_on_avazu_eval_online_gauc_ctr.config
Labels: ci_test_passed, ci_py3_test_passed

#166 [feat]: add f1 reweighted loss for multi tower model & make odpsRtpInput support extra input column, like 'sample_weight
  docs/source/feature/rtp_fg.md
  docs/source/models/multi_tower.md
  easy_rec/python/builders/loss_builder.py
  easy_rec/python/input/odps_rtp_input.py
  easy_rec/python/loss/f1_reweight_loss.py
  easy_rec/python/model/multi_tower.py
  easy_rec/python/model/rank_model.py
  easy_rec/python/protos/easy_rec_model.proto
  easy_rec/python/protos/loss.proto
  easy_rec/python/test/loss_test.py
  easy_rec/version.py
  samples/model_config/multi_tower_on_taobao.config
Labels: ci_test_passed

#168 [bugfix]: fix potentional import exception in ut
  scripts/ci_test.sh
  scripts/ci_test_change_files.py
Labels: ci_test_passed, ci_py3_test_passed

#167 [feat]:add distribute eval for ds environment
  easy_rec/python/core/distribute_metrics.py
  easy_rec/python/eval.py
  easy_rec/python/model/collaborative_metric_learning.py
  easy_rec/python/utils/distribution_utils.py
Labels: ci_test_passed, ci_py3_test_passed

#159 [Fea] Add pre-check
  docs/source/index.rst
  docs/source/pre_check.md
  easy_rec/python/input/batch_tfrecord_input.py
  easy_rec/python/input/csv_input.py
  easy_rec/python/input/csv_input_ex.py
  easy_rec/python/input/csv_input_v2.py
  easy_rec/python/input/datahub_input.py
  easy_rec/python/input/dummy_input.py
  easy_rec/python/input/hive_input.py
  easy_rec/python/input/input.py
  easy_rec/python/input/kafka_input.py
  easy_rec/python/input/odps_input.py
  easy_rec/python/input/odps_input_v2.py
  easy_rec/python/input/odps_input_v3.py
  easy_rec/python/input/odps_rtp_input.py
  easy_rec/python/input/odps_rtp_input_v2.py
  easy_rec/python/input/rtp_input.py
  easy_rec/python/input/rtp_input_v2.py
  easy_rec/python/input/tfrecord_input.py
  easy_rec/python/layers/seq_input_layer.py
  easy_rec/python/main.py
  easy_rec/python/test/pre_check_test.py
  easy_rec/python/tools/pre_check.py
  easy_rec/python/train_eval.py
  easy_rec/python/utils/check_utils.py
  easy_rec/python/utils/test_utils.py
  easy_rec/version.py
  pai_jobs/easy_rec_flow/easy_rec.lua
  pai_jobs/run.py
  setup.py
Labels: ci_test_passed, ci_py3_test_passed

#169 [feat]: add f1 reweighted loss for multi tower model & make odpsRtpInput support extra input column, like 'sample_weight
  docs/source/develop.md
  docs/source/eval.md
  docs/source/feature/rtp_fg.md
  docs/source/feature/rtp_native.md
  docs/source/metrics.md
  docs/source/models/dssm.md
  docs/source/models/dssm_neg_sampler.md
  docs/source/models/multi_tower.md
  docs/source/models/user_define.md
  docs/source/quick_start/mc_tutorial.md
  docs/source/quick_start/mc_tutorial_inner.md
  easy_rec/python/builders/loss_builder.py
  easy_rec/python/compat/estimator_train.py
  easy_rec/python/compat/feature_column/feature_column_v2.py
  easy_rec/python/compat/ops.py
  easy_rec/python/feature_column/feature_column.py
  easy_rec/python/input/hive_input.py
  easy_rec/python/input/input.py
  easy_rec/python/input/odps_rtp_input.py
  easy_rec/python/input/odps_rtp_input_v2.py
  easy_rec/python/layers/utils.py
  easy_rec/python/loss/f1_reweight_loss.py
  easy_rec/python/main.py
  easy_rec/python/model/dssm.py
  easy_rec/python/model/easy_rec_estimator.py
  easy_rec/python/model/multi_tower.py
  easy_rec/python/model/multi_tower_bst.py
  easy_rec/python/model/rank_model.py
  easy_rec/python/protos/easy_rec_model.proto
  easy_rec/python/protos/hive_config.proto
  easy_rec/python/protos/loss.proto
  easy_rec/python/test/export_test.py
  easy_rec/python/test/hive_input_test.py
  easy_rec/python/test/loss_test.py
  easy_rec/python/test/odps_run.py
  easy_rec/python/test/odps_test_prepare.py
  easy_rec/python/test/train_eval_test.py
  easy_rec/python/test/util_test.py
  easy_rec/python/tools/add_feature_info_to_config.py
  easy_rec/python/utils/estimator_utils.py
  easy_rec/python/utils/expr_util.py
  easy_rec/python/utils/hpo_util.py
  git-lfs/git_lfs.py
  pai_jobs/run.py
  requirements/docs.txt
  requirements/extra.txt
  requirements/runtime.txt
  requirements/tests.txt
  samples/model_config/multi_tower_on_taobao.config
  setup.cfg
Labels: ci_test_failed, ci_py3_test_passed

#171 [bugfix]: fix bug for distribute metrics
  easy_rec/python/core/distribute_metrics.py
Labels: ci_test_passed, ci_py3_test_passed

#178 [bugfix] update introduction image.
  docs/images/intro.png
Labels: ci_test_passed, ci_py3_test_passed
