Repository alibaba/EasyRec, pull requests merged in 2022-09, with the labels that each got.

#272 [feature] add dlc tutorial
  docs/images/quick_start/easyrec_dlc_1.png
  docs/images/quick_start/easyrec_dlc_2.png
  docs/images/quick_start/easyrec_dlc_5.png
  docs/images/quick_start/easyrec_dlc_7.png
  docs/images/quick_start/easyrec_dlc_8.png
  docs/images/quick_start/easyrec_dlc_9.png
  docs/images/quick_start/easyrec_dlc_tensorboard_1.png
  docs/images/quick_start/easyrec_dlc_tensorboard_2.png
  docs/source/quick_start/dlc_tutorial.md
Labels: ci_test_passed, ci_py3_test_passed, ci_py3_tf25_test_passed

#273 update quick_start.rst
  docs/source/quick_start.rst
Labels: ci_test_passed, ci_py3_test_passed, ci_py3_tf25_test_passed

#274 update dlc_tutorial.md
  docs/source/quick_start/dlc_tutorial.md
Labels: ci_test_passed, ci_py3_test_passed, ci_py3_tf25_test_passed

#199 [bugfix]: update feature.rst
  docs/source/feature/feature.rst
Labels: ci_test_passed, ci_py3_test_passed

#277 [bugfix] export user_emb and item_emb used to calculate simularity
  easy_rec/python/model/match_model.py
Labels: ci_test_passed, ci_py3_test_passed, ci_py3_tf25_test_passed

#278 [doc] fix rtp_native documentation: add reserve_default: false in fg.json
  docs/source/feature/rtp_native.md
Labels: ci_test_passed, ci_py3_test_passed, ci_py3_tf25_test_passed

#279 [feat] add hitrate hdfs
  easy_rec/python/tools/hit_rate_ds.py
Labels: ci_py3_test_passed

#281 Fix bug of HiveRtpInput triggered when sample_weight is used
  easy_rec/python/input/hive_rtp_input.py
Labels: ci_test_passed, ci_py3_test_passed, ci_py3_tf25_test_passed

#282 Fix bug of hive_rtp_input triggered when sample weight is used
  easy_rec/python/input/hive_rtp_input.py
Labels: ci_test_passed, ci_py3_test_passed, ci_py3_tf25_test_passed

#286 [bugfix]: fix kafka custom op import error on non-linux system
  easy_rec/__init__.py
  easy_rec/python/ops/gen_kafka_ops.py
Labels: ci_test_passed, ci_py3_test_passed, ci_py3_tf25_test_passed

#285 [Feat] Support csv with header
  .git_bin_path
  .git_bin_url
  easy_rec/python/inference/predictor.py
  easy_rec/python/input/csv_input.py
  easy_rec/python/predict.py
  easy_rec/python/test/predictor_test.py
Labels: ci_test_passed, ci_py3_test_passed, ci_py3_tf25_test_passed

#283 [bugfix]:fix sequence feature last layer bug
  .git_bin_url
  easy_rec/python/layers/dnn.py
  easy_rec/python/layers/input_layer.py
  easy_rec/python/layers/seq_input_layer.py
  easy_rec/python/layers/sequence_feature_layer.py
  easy_rec/python/model/multi_tower_bst.py
  easy_rec/python/model/multi_tower_din.py
  easy_rec/python/test/train_eval_test.py
  setup.cfg
Labels: ci_test_passed, ci_py3_tf25_test_passed

#287 [feature] add designer doc
  docs/images/designer_1.png
  docs/images/designer_2.png
  docs/source/feature/pai_rec_callback_conf.md
  docs/source/feature/rtp_fg.md
  docs/source/online_train.md
  docs/source/proto.html
  docs/source/quick_start.rst
  docs/source/quick_start/designer_tutorial.md
  scripts/build_docs.sh
Labels: ci_test_passed, ci_py3_test_passed, ci_py3_tf25_test_passed

#289 update hpo docs
  docs/images/automl/nni_metric.png
  docs/images/automl/nni_stop.png
  docs/source/automl/pai_nni_hpo.md
  easy_rec/__init__.py
  easy_rec/python/ops/gen_kafka_ops.py
Labels: ci_test_passed, ci_py3_test_passed, ci_py3_tf25_test_passed
