Repository alibaba/EasyRec, pull requests merged in 2022-07, with the labels that each got.

#224 [feat]Optimize io cost of hiveinput and add hiveparquetinput
  docs/source/models/dssm_neg_sampler.md
  easy_rec/python/inference/predictor.py
  easy_rec/python/input/hive_input.py
  easy_rec/python/input/hive_parquet_input.py
  easy_rec/python/input/hive_rtp_input.py
  easy_rec/python/predict.py
  easy_rec/python/protos/dataset.proto
  easy_rec/python/protos/hive_config.proto
  easy_rec/python/tools/add_feature_info_to_config.py
  easy_rec/python/utils/hive_utils.py
Labels: ci_test_passed, ci_py3_test_passed

#228 update incremental_train.md
  docs/source/incremental_train.md
Labels: ci_test_passed, ci_py3_test_passed

#231 [feature]: add support for frequency filter and steps_to_alive for embedding variable
  easy_rec/python/compat/feature_column/feature_column.py
  easy_rec/python/compat/feature_column/feature_column_v2.py
  easy_rec/python/feature_column/feature_column.py
  easy_rec/python/layers/input_layer.py
  easy_rec/python/layers/seq_input_layer.py
  easy_rec/python/model/easy_rec_model.py
  easy_rec/python/model/multi_tower_bst.py
  easy_rec/python/model/multi_tower_din.py
  easy_rec/python/protos/easy_rec_model.proto
  easy_rec/python/protos/feature_config.proto
  samples/model_config/fg_ev_v2.config
  samples/model_config/taobao_fg_ev.config
  samples/model_config/taobao_fg_ev_v2.config
Labels: ci_test_passed, ci_py3_test_passed

#230 [bugfix]: update export.proto
  easy_rec/python/protos/export.proto
Labels: ci_test_passed, ci_py3_test_passed

#216 [bugfix]: update data layer document, add more comments
  docs/source/feature/data.md
Labels: ci_test_passed, ci_py3_test_passed

#232 [feat]: fix bug of fail to assign default value of rtp input field
  easy_rec/python/input/hive_parquet_input.py
  easy_rec/python/input/hive_rtp_input.py
  easy_rec/python/input/odps_rtp_input.py
  easy_rec/python/input/rtp_input.py
  easy_rec/python/utils/input_utils.py
  easy_rec/version.py
Labels: ci_py3_test_passed

#229 [feat]Support gnn on datascience
  .git_bin_path
  .git_bin_url
  docs/source/models/cmbf.md
  easy_rec/python/core/sampler.py
  easy_rec/python/eval.py
  easy_rec/python/inference/predictor.py
  easy_rec/python/input/hive_rtp_input.py
  easy_rec/python/protos/dataset.proto
  easy_rec/python/test/train_eval_test.py
  easy_rec/python/tools/split_model_pai.py
  easy_rec/python/train_eval.py
  easy_rec/python/utils/config_util.py
  easy_rec/python/utils/ds_util.py
  easy_rec/python/utils/estimator_utils.py
  easy_rec/python/utils/test_utils.py
Labels: ci_test_passed, ci_py3_test_passed

#237 [bugfix]: fix bug of softmax_loss_with_negative_mining loss
  easy_rec/python/loss/softmax_loss_with_negative_mining.py
  easy_rec/python/test/loss_test.py
Labels: ci_py3_test_passed

#235 Features/cmbf
  docs/source/models/cmbf.md
  docs/source/models/dbmtl.md
  easy_rec/python/layers/cmbf.py
  easy_rec/python/model/cmbf.py
  easy_rec/python/model/dbmtl.py
  easy_rec/python/protos/layer.proto
  easy_rec/version.py
  samples/model_config/cmbf_on_movielens_has_other_feature.config
  samples/model_config/cmbf_on_movielens_only_image_feature.config
  samples/model_config/cmbf_on_movielens_only_text_feature.config
Labels: ci_test_passed, ci_py3_test_passed

#241 [bugfix] add support tf2 metrics
  docs/source/feature/data.md
  easy_rec/python/compat/feature_column/feature_column.py
  easy_rec/python/compat/feature_column/feature_column_v2.py
  easy_rec/python/core/easyrec_metrics/__init__.py
  easy_rec/python/feature_column/feature_column.py
  easy_rec/python/input/odps_rtp_input.py
  easy_rec/python/layers/input_layer.py
  easy_rec/python/layers/seq_input_layer.py
  easy_rec/python/main.py
  easy_rec/python/model/multi_tower_bst.py
  easy_rec/python/model/multi_tower_din.py
  easy_rec/python/protos/feature_config.proto
  easy_rec/python/utils/io_util.py
Labels: ci_test_passed, ci_py3_test_passed

#247 [fix]: fix_code_style_and_docs
  docs/source/models/cmbf.md
  docs/source/models/dbmtl.md
  easy_rec/python/core/sampler.py
  easy_rec/python/layers/cmbf.py
  easy_rec/python/loss/softmax_loss_with_negative_mining.py
  easy_rec/python/test/loss_test.py
  easy_rec/python/tools/hit_rate_pai.py
  easy_rec/python/utils/estimator_utils.py
Labels: ci_test_passed, ci_py3_test_passed

#252 [bugfix]:fix bug for distribute eval worker hangs
  easy_rec/python/main.py
  easy_rec/version.py
Labels: ci_test_passed, ci_py3_test_passed

#253 Eas predict client doc fix
  docs/source/feature/rtp_fg.md
Labels: ci_test_passed, ci_py3_test_passed

#254 [bugfix]: fix markdown version
  requirements/docs.txt
Labels: ci_test_passed, ci_py3_test_passed

#255 [feature]: add support for tf25 py3 test
  .github/workflows/ci_py3_tf25.yml
  docs/source/feature/rtp_fg.md
  easy_rec/python/compat/layers.py
  easy_rec/python/layers/multihead_cross_attention.py
  easy_rec/python/loss/softmax_loss_with_negative_mining.py
  easy_rec/python/test/loss_test.py
  easy_rec/python/test/train_eval_test.py
  easy_rec/python/tools/feature_selection.py
  requirements/docs.txt
Labels: ci_test_passed, ci_py3_test_passed, ci_py3_tf25_test_passed

#246 [bugfix]: limit the time of a single test execution
  easy_rec/python/test/run.py
  easy_rec/python/test/train_eval_test.py
  easy_rec/python/utils/test_utils.py
Labels: ci_test_passed, ci_py3_test_passed

#234 [bugfix]: fix embedding variable restore bug
  easy_rec/python/model/easy_rec_model.py
Labels: ci_test_passed, ci_py3_test_passed, ci_py3_tf25_test_passed

#233 [bugfix] fix share not used bug
  .git_bin_path
  .git_bin_url
  easy_rec/python/feature_column/feature_column.py
  easy_rec/python/test/train_eval_test.py
  easy_rec/python/utils/convert_rtp_fg.py
  git-lfs/git_lfs.py
  samples/model_config/share_not_used.config
Labels: ci_test_passed, ci_py3_test_passed

#258 Fix bug of sequence feature rtp input
  docs/source/feature/feature.rst
  docs/source/train.md
  easy_rec/python/utils/config_util.py
  samples/model_config/share_not_used.config
Labels: ci_test_passed, ci_py3_tf25_test_passed

#259 [bugfix] add missing constants
  easy_rec/python/utils/convert_rtp_fg.py
Labels: ci_test_passed, ci_py3_test_passed, ci_py3_tf25_test_passed

#256 update hpo nni
  docs/images/automl/nni-failed1.png
  docs/images/automl/pai_nni_log.jpg
  docs/images/automl/pai_nni_modify.jpg
  docs/source/automl/pai_nni_hpo.md
  easy_rec/python/hpo_nni/__init__.py
  easy_rec/python/hpo_nni/pai_nni/__init__.py
  easy_rec/python/hpo_nni/pai_nni/code/__init__.py
  easy_rec/python/hpo_nni/pai_nni/config/.ossutilconfig
  easy_rec/python/hpo_nni/pai_nni/config/easyrec_cmd_config_begin
  easy_rec/python/hpo_nni/pai_nni/config/easyrec_cmd_config_test
  easy_rec/python/hpo_nni/pai_nni/config/metric_config
  easy_rec/python/hpo_nni/pai_nni/config/odps_config.ini
  easy_rec/python/hpo_nni/pai_nni/source_begin/config.yml
  easy_rec/python/hpo_nni/pai_nni/source_begin/run_begin.py
  easy_rec/python/hpo_nni/pai_nni/source_begin/search_space.json
  easy_rec/python/hpo_nni/pai_nni/source_finetune/config.yml
  easy_rec/python/model/easy_rec_model.py
  easy_rec/python/test/pai_nni_test.py
  easy_rec/python/test/run.py
  easy_rec/python/test/train_eval_test.py
  easy_rec/python/utils/estimator_utils.py
  easy_rec/python/utils/test_utils.py
  hpo_nni/__init__.py
  hpo_nni/core/__init__.py
  hpo_nni/core/metric_utils.py
  hpo_nni/core/modify_pipeline_config.py
  hpo_nni/core/pai_assessor.py
  hpo_nni/core/pai_nni_test.py
  hpo_nni/core/pyodps_utils.py
  hpo_nni/core/utils.py
  hpo_nni/requirements.txt
  hpo_nni/search/begin/config.yml
  hpo_nni/search/begin/config_begin.ini
  hpo_nni/search/begin/run_begin.py
  hpo_nni/search/begin/search_space.json
  hpo_nni/search/finetune/config.yml
  hpo_nni/search/finetune/config_finetune.ini
  hpo_nni/search/finetune/run_finetune.py
  hpo_nni/search/finetune/search_space.json
  samples/hpo/pipeline.config
  samples/hpo/pipeline_finetune.config
  samples/hpo/search_space.json
  setup.cfg
Labels: ci_test_passed, ci_py3_test_passed, ci_py3_tf25_test_passed
