Repository alibaba/EasyRec, pull requests merged in 2022-11, with the labels that each got.

#298 [feat]: CSVPredictor support embedding input
  .git_bin_path
  .git_bin_url
  easy_rec/python/inference/predictor.py
  easy_rec/python/predict.py
  easy_rec/python/test/predictor_test.py
Labels: ci_test_passed

#299 update nni hpo docs
  docs/images/automl/best-model.png
  docs/images/automl/exp-list.png
  docs/images/automl/nni-compare.png
  docs/images/automl/nni-install.png
  docs/source/automl/pai_nni_hpo.md
  easy_rec/python/test/predictor_test.py
  easy_rec/python/test/train_eval_test.py
  setup.cfg
Labels: ci_py3_test_passed, ci_py3_tf25_test_passed

#302 [bugfix]: Fix dist eval ps high memory bug
  easy_rec/python/main.py
  easy_rec/python/model/easy_rec_estimator.py
  easy_rec/version.py
Labels: ci_test_passed, ci_py3_test_passed

#307 update hpo docs and remove tensorflow in runtime.txt
  docs/source/automl/pai_nni_hpo.md
  easy_rec/python/main.py
  easy_rec/version.py
  requirements/runtime.txt
Labels: ci_test_passed, ci_py3_test_passed, ci_py3_tf25_test_passed

#309 [bugfix]: fix negative sample using hive input bug
  easy_rec/python/utils/config_util.py
Labels: ci_test_passed, ci_py3_test_passed, ci_py3_tf25_test_passed

#310 bug fix of GAUC/SessionAuc when the id field is not configured in feature groups
  easy_rec/python/input/batch_tfrecord_input.py
  easy_rec/python/input/criteo_input.py
  easy_rec/python/input/csv_input.py
  easy_rec/python/input/csv_input_ex.py
  easy_rec/python/input/csv_input_v2.py
  easy_rec/python/input/datahub_input.py
  easy_rec/python/input/dummy_input.py
  easy_rec/python/input/hive_input.py
  easy_rec/python/input/hive_parquet_input.py
  easy_rec/python/input/hive_rtp_input.py
  easy_rec/python/input/input.py
  easy_rec/python/input/kafka_input.py
  easy_rec/python/input/odps_input.py
  easy_rec/python/input/odps_input_v2.py
  easy_rec/python/input/odps_input_v3.py
  easy_rec/python/input/odps_rtp_input.py
  easy_rec/python/input/odps_rtp_input_v2.py
  easy_rec/python/input/rtp_input.py
  easy_rec/python/input/rtp_input_v2.py
  easy_rec/python/input/tfrecord_input.py
  easy_rec/python/main.py
  easy_rec/python/test/train_eval_test.py
  samples/model_config/multi_tower_on_taobao_session_auc.config
  setup.cfg
Labels: ci_test_passed, ci_py3_test_passed, ci_py3_tf25_test_passed

#314 [doc]: add docs for processor
  docs/images/processor/easy_rec_processor_1.png
  docs/images/processor/easy_rec_processor_2.png
  docs/images/processor/easy_rec_processor_3.png
  docs/source/feature/feature.rst
  docs/source/feature/rtp_fg.md
  docs/source/index.rst
  docs/source/predict/processor.md
  docs/source/predict/在线预测.md
Labels: ci_py3_test_passed

#315 bug fix of GAUC/Session AUC metric when the id field is not configurated in feature groups
  easy_rec/python/input/input.py
Labels: ci_test_passed, ci_py3_test_passed, ci_py3_tf25_test_passed

#317 [docs] update fine_tune_checkpoint specification
  docs/source/incremental_train.md
Labels: ci_test_passed, ci_py3_test_passed, ci_py3_tf25_test_passed

#318 [bugfix]: Fix dist eval ps high memory
  easy_rec/python/main.py
  easy_rec/python/test/train_eval_test.py
  easy_rec/version.py
  setup.cfg
Labels: ci_py3_tf25_test_passed
