Repository alibaba/EasyRec, pull requests merged in 2022-05, with the labels that each got.

#179 [bugfix]: update intro img
  docs/images/intro.png
Labels: ci_test_passed, ci_py3_test_passed

#170 [bugfix] Fix label dtype error with rtp input
  easy_rec/python/builders/loss_builder.py
  easy_rec/python/inference/predictor.py
  easy_rec/python/input/rtp_input.py
  easy_rec/python/test/train_eval_test.py
  easy_rec/version.py
  samples/model_config/rocket_launching_with_rtp_input.config
Labels: ci_test_passed, ci_py3_test_passed

#180 [bugfix]: fix the bug that not specify num_steps do not work.
  easy_rec/python/main.py
Labels: ci_test_passed, ci_py3_test_passed

#128 add mlperf config on criteo
  easy_rec/python/input/criteo_binary_reader.py
  easy_rec/python/input/criteo_input.py
  easy_rec/python/input/input.py
  easy_rec/python/input/odps_rtp_input.py
  easy_rec/python/input/odps_rtp_input_v2.py
  easy_rec/python/input/rtp_input.py
  easy_rec/python/layers/seq_input_layer.py
  easy_rec/python/main.py
  easy_rec/python/model/collaborative_metric_learning.py
  easy_rec/python/model/easy_rec_estimator.py
  easy_rec/python/protos/data_source.proto
  easy_rec/python/protos/dataset.proto
  easy_rec/python/protos/pipeline.proto
  easy_rec/python/test/hive_input_test.py
  easy_rec/python/test/pre_check_test.py
  easy_rec/python/test/train_eval_test.py
  easy_rec/python/tools/criteo/__init__.py
  easy_rec/python/tools/criteo/convert_data.py
  easy_rec/python/tools/pre_check.py
  easy_rec/python/train_eval.py
  easy_rec/python/utils/check_utils.py
  easy_rec/python/utils/distribution_utils.py
  easy_rec/python/utils/test_utils.py
  pai_jobs/run.py
  samples/model_config/dlrm_on_criteo.config
Labels: ci_test_passed, ci_py3_test_passed

#188 fix bug of wrong variable name
  easy_rec/python/input/odps_rtp_input.py
Labels: ci_test_passed, ci_py3_test_passed

#191 [doc]: autocross doc update
  docs/source/automl/auto_cross_emr.md
Labels: ci_test_passed, ci_py3_test_passed

#186 feat: Refactor predictor
  .git_bin_path
  .git_bin_url
  docs/source/models/mind.md
  docs/source/pre_check.md
  docs/source/proto.html
  easy_rec/python/builders/loss_builder.py
  easy_rec/python/core/distribute_metrics.py
  easy_rec/python/core/sampler.py
  easy_rec/python/eval.py
  easy_rec/python/inference/predictor.py
  easy_rec/python/input/batch_tfrecord_input.py
  easy_rec/python/input/csv_input.py
  easy_rec/python/input/csv_input_v2.py
  easy_rec/python/input/datahub_input.py
  easy_rec/python/input/dummy_input.py
  easy_rec/python/input/hive_input.py
  easy_rec/python/input/input.py
  easy_rec/python/input/odps_input.py
  easy_rec/python/input/odps_input_v2.py
  easy_rec/python/input/odps_input_v3.py
  easy_rec/python/input/rtp_input.py
  easy_rec/python/input/tfrecord_input.py
  easy_rec/python/main.py
  easy_rec/python/model/mind.py
  easy_rec/python/predict.py
  easy_rec/python/test/hive_input_test.py
  easy_rec/python/test/pre_check_test.py
  easy_rec/python/test/predictor_test.py
  easy_rec/python/test/train_eval_test.py
  easy_rec/python/train_eval.py
  easy_rec/python/utils/check_utils.py
  easy_rec/python/utils/config_util.py
  easy_rec/python/utils/hive_utils.py
  easy_rec/python/utils/tf_utils.py
  easy_rec/version.py
  pai_jobs/run.py
Labels: ci_py3_test_passed

#198 [bugfix]: fix hpo param convert bug: issues#155
  easy_rec/python/test/hpo_test.py
  easy_rec/python/utils/config_util.py
  samples/hpo/hpo_param_v13.json
  samples/hpo/hpo_param_v14.json
Labels: ci_test_passed, ci_py3_test_passed

#197 [feature]: allow finer control over embedding variable
  easy_rec/python/feature_column/feature_column.py
  easy_rec/python/protos/feature_config.proto
  easy_rec/python/utils/fg_util.py
Labels: ci_test_passed, ci_py3_test_passed

#190 feat: delete feature with one value
  easy_rec/python/tools/add_feature_info_to_config.py
Labels: ci_test_passed
