Repository alibaba/EasyRec, pull requests merged in 2022-12, with the labels that each got.

#319 [release] Update version.py
  easy_rec/version.py
Labels: ci_py3_tf25_test_passed

#322 [feature]: update hpo docs and 0.1.6 support one-click-retry-multi-failed-trials
  docs/images/automl/hyper.jpg
  docs/images/automl/retry_trial.jpg
  docs/source/automl/pai_nni_hpo.md
  easy_rec/version.py
Labels: ci_test_failed, ci_py3_test_failed

#327 [bugfix] fix typo in vector retrieve
  easy_rec/python/inference/vector_retrieve.py
Labels: ci_test_passed, ci_py3_test_passed, ci_py3_tf25_test_passed

#326 [feature] add direct cmd args for update easyrec config
  docs/source/train.md
  easy_rec/python/test/train_eval_test.py
  easy_rec/python/train_eval.py
  easy_rec/python/utils/config_util.py
  easy_rec/python/utils/test_utils.py
Labels: ci_test_passed, ci_py3_test_passed, ci_py3_tf25_test_passed

#325 [bugfix] fix sync train not exit bug due to uneven dataset shard caused by filter invalid samples
  easy_rec/python/compat/sync_replicas_optimizer.py
  easy_rec/python/model/easy_rec_estimator.py
Labels: ci_test_passed, ci_py3_test_passed, ci_py3_tf25_test_passed
