Repository alibaba/EasyRec, pull requests merged in 2023-05, with the labels that each got.

#362 [feat]: add dice activation for dnn layer
  docs/source/train.md
  easy_rec/python/compat/early_stopping.py
  easy_rec/python/compat/weight_decay_optimizers.py
  easy_rec/python/feature_column/feature_column.py
  easy_rec/python/input/input.py
  easy_rec/python/layers/cmbf.py
  easy_rec/python/layers/common_layers.py
  easy_rec/python/layers/dnn.py
  easy_rec/python/layers/multihead_cross_attention.py
  easy_rec/python/layers/uniter.py
  easy_rec/python/model/collaborative_metric_learning.py
  easy_rec/python/model/match_model.py
  easy_rec/python/test/train_eval_test.py
  easy_rec/python/utils/activation.py
  samples/model_config/dbmtl_on_taobao_with_multi_loss.config
  setup.cfg
Labels: ci_test_passed

#366 [release] release v0.6.3
  easy_rec/version.py
Labels: ci_test_passed, ci_py3_test_passed, ci_py3_tf25_test_passed, code_style_test_passed

#357 [bugfix]: fix mount directory checkpoint cache problem for data science platform
  easy_rec/python/utils/ds_util.py
Labels: ci_py3_test_passed

#367 添加EasyRec-Demo实验 (examples/)
  .git_bin_url
  examples/configs/autoint_on_movielens.config
  examples/configs/dcn_on_movielens.config
  examples/configs/deepfm_on_criteo.config
  examples/configs/deepfm_on_movielens.config
  examples/configs/dssm_on_books.config
  examples/configs/dssm_on_books_negative_sample.config
  examples/configs/fm_on_criteo.config
  examples/configs/mind_on_books.config
  examples/configs/mind_on_books_negative_sample.config
  examples/configs/readme.md
  examples/configs/wide_and_deep_on_movielens.config
  examples/data/amazon_books_data/download_and_process.sh
  examples/data/amazon_books_data/process_amazon.py
  examples/data/amazon_books_data/readme.md
  examples/data/criteo/download_and_process.sh
  examples/data/criteo/process_criteo_kaggle.py
  examples/data/criteo/readme.md
  examples/data/movielens_1m/download_and_process.sh
  examples/data/movielens_1m/process_ml_1m.py
  examples/data/movielens_1m/readme.md
  examples/match_model/dssm.md
  examples/match_model/dssm_negative_sample.md
  examples/match_model/mind.md
  examples/match_model/mind_negative_sample.md
  examples/match_model/readme.md
  examples/rank_model/DeepFM.md
  examples/rank_model/autoint.md
  examples/rank_model/dcn.md
  examples/rank_model/fm.md
  examples/rank_model/readme.md
  examples/rank_model/wide_and_deep.md
  examples/readme.md
  setup.cfg
Labels: ci_test_passed, ci_py3_test_passed, ci_py3_tf25_test_passed, code_style_test_passed

#369 Update REAMDE and examples
  README.md
  examples/readme.md
Labels: ci_test_passed, ci_py3_test_passed, code_style_test_passed

#370 fix predict out of dssm model
  easy_rec/python/model/dssm.py
Labels: ci_test_passed, ci_py3_test_passed, ci_py3_tf25_test_passed, code_style_test_passed

#371 fix predict shape of logits and probs in MIND model
  easy_rec/python/model/mind.py
Labels: ci_test_passed, ci_py3_test_passed, ci_py3_tf25_test_passed, code_style_test_passed

#372 添加examples下数据集的下载链接，并适配不同操作系统
  examples/data/amazon_books_data/download_and_process.sh
  examples/data/amazon_books_data/readme.md
  examples/data/criteo/download_and_process.sh
  examples/data/criteo/readme.md
  examples/data/movielens_1m/download_and_process.sh
  examples/data/movielens_1m/readme.md
  examples/readme.md
Labels: ci_test_passed, ci_py3_test_passed, ci_py3_tf25_test_passed, code_style_test_passed

#374 fix bug in match model when calculate sim()
  easy_rec/python/model/dssm.py
  easy_rec/python/model/match_model.py
  easy_rec/python/model/mind.py
Labels: ci_test_passed, ci_py3_test_passed, ci_py3_tf25_test_passed, code_style_test_passed
