Repository alibaba/EasyRec, pull requests merged in 2023-02, with the labels that each got.

#336 Bugfix：fix bug of embedding regularization
  easy_rec/python/layers/input_layer.py
  easy_rec/version.py
Labels: ci_test_passed, ci_py3_test_passed, ci_py3_tf25_test_passed, code_style_test_passed

#335 [bug fix]: fix bug of multiple losses of rank model
  easy_rec/python/model/multi_task_model.py
  easy_rec/python/model/rank_model.py
Labels: ci_test_passed, ci_py3_test_passed, ci_py3_tf25_test_passed

#341 [bugfix]: fix the problem of can not display code snippets in document
  docs/source/feature/feature.rst
Labels: ci_test_passed, ci_py3_test_passed, ci_py3_tf25_test_passed, code_style_test_passed

#342 [bugfix]:fix layer for sequence feature
  easy_rec/python/layers/sequence_feature_layer.py
  easy_rec/python/test/train_eval_test.py
  samples/model_config/dbmtl_on_multi_numeric_boundary_allow_key_transform_multi_seq.config
  setup.cfg
Labels: ci_test_passed, ci_py3_test_passed, ci_py3_tf25_test_passed, code_style_test_passed

#334 [bugfix]: fix bug for graphlearn dist eval
  easy_rec/python/main.py
Labels: ci_test_passed, ci_py3_test_passed, ci_py3_tf25_test_passed

#344 [feat]: add support seq transform padding and dnn
  docs/source/feature/feature.rst
  easy_rec/python/layers/sequence_feature_layer.py
  easy_rec/python/main.py
  easy_rec/python/protos/feature_config.proto
  samples/model_config/dbmtl_on_multi_numeric_boundary_allow_key_transform_dnn.config
Labels: ci_test_passed, ci_py3_test_passed, ci_py3_tf25_test_passed, code_style_test_passed

#346 [bugfix]: fix a bug of loading checkpoint panic when graph meta is not written
  easy_rec/python/utils/estimator_utils.py
  pai_jobs/deploy_ext.sh
Labels: ci_test_passed, ci_py3_test_passed, ci_py3_tf25_test_passed, code_style_test_passed

#337 [bugfix]: fix ds osshdfsmnt output
  easy_rec/python/tools/hit_rate_ds.py
Labels: code_style_test_passed

#348 [bugfix]: Fix clear model, predict two model, sync on pai.
  easy_rec/python/compat/sync_replicas_optimizer.py
  easy_rec/python/inference/predictor.py
  pai_jobs/run.py
Labels: ci_test_passed, ci_py3_test_passed, ci_py3_tf25_test_passed, code_style_test_passed
