Repository alibaba/EasyRec, pull requests merged in 2023-07, with the labels that each got.

#393 Features/add data link on mc tutorial inner
  docs/source/quick_start/mc_tutorial.md
  docs/source/quick_start/mc_tutorial_inner.md
Labels: ci_test_passed, ci_py3_test_passed, ci_py3_tf25_test_passed, code_style_test_passed

#397 [feat] update version to 0.6.4
  easy_rec/python/inference/predictor.py
  easy_rec/version.py
Labels: ci_py3_tf25_test_passed

#395 Features/fix docker
  docs/source/quick_start/local_tutorial.md
  examples/configs/deepfm_on_criteo.config
  examples/configs/deepfm_on_movielens.config
  examples/readme.md
Labels: ci_test_passed, ci_py3_test_passed, ci_py3_tf25_test_passed, code_style_test_passed

#398 [feat]: place embedding on cpu if necessary
  easy_rec/python/input/input.py
  easy_rec/python/layers/input_layer.py
  easy_rec/python/layers/sequence_feature_layer.py
  easy_rec/python/model/easy_rec_model.py
  easy_rec/python/test/train_eval_test.py
  easy_rec/python/utils/__init__.py
  easy_rec/python/utils/meta_graph_editor.py
  pai_jobs/run.py
Labels: ci_test_passed, ci_py3_test_passed, ci_py3_tf25_test_passed, code_style_test_passed

#399 [feature]: add continue train on evaluation data
  easy_rec/python/compat/estimator_train.py
  easy_rec/python/compat/sync_replicas_optimizer.py
  easy_rec/python/main.py
  easy_rec/python/test/train_eval_test.py
  easy_rec/python/train_eval.py
  easy_rec/python/utils/estimator_utils.py
  easy_rec/python/utils/test_utils.py
  samples/model_config/multi_tower_on_taobao_unblanace.config
Labels: ci_py3_tf25_test_passed

#403 [bugfix] skip label and comment, as it requires special permessions and is not necessary
  .github/workflows/ci.yml
  .github/workflows/ci_py3.yml
  .github/workflows/ci_py3_tf25.yml
Labels: code_style_test_passed

#405 [feat] update nni docs: add resume/tensorboard
  docs/images/automl/nni_tensorboard.jpg
  docs/source/automl/finetune_config.md
  docs/source/automl/hpo_config.md
  docs/source/automl/hpo_res.md
  docs/source/automl/pai_nni_hpo.md
  easy_rec/python/compat/early_stopping.py
  easy_rec/python/test/train_eval_test.py
  setup.cfg
Labels: code_style_test_passed

#408 update nni docs
  docs/source/automl/pai_nni_hpo.md
Labels: code_style_test_passed
